import { extendTheme } from "@chakra-ui/react";
import { Button } from "./components/Button";
import { Input } from "./components/Input";
import { Link } from "./components/Link";

const breakpoints = {
  sm: '410px',
  md: '768px',
  lg: '960px',
  xl: '1280px',
  '2xl': '1536px',
  '3xl': '1680px',
  '4xl': '1920px',
}

const theme = extendTheme({
  breakpoints,
  components: {
    Button, 
    Input, 
    Link,
  },
  
  sizes: {
    container: {
      sm: '960px',
      md: '1040px',
      lg: '1160px',
      xl: '1240px',
      xxl: '1600px',
    },
  },
  colors: {
    primary: {
      0: '#000000',
      10: '#231b00',
      20: '#3c2f00',
      25: '#493a00',
      30: '#574500',
      35: '#655000',
      40: '#735c00',
      50: '#907400',
      60: '#ae8d10',
      70: '#cba82f',
      80: '#e8c349',
      90: '#ffe084',
      95: '#fff0ca',
      98: '#fff8f0',
      99: '#fffbff',
      100: '#ffffff',
    },
    neutral: {
      0: '#000000',
      4: "#12110D",
      5: "#12110D",
      10: "#1D1B17",
      15: "#282521",
      20: "#32302C",
      25: "#3E3B36",
      30: "#494642",
      35: "#55524D",
      40: "#615E59",
      50: "#7A7671",
      60: "#94908A",
      70: "#AFAAA4",
      80: "#CBC6BF",
      90: "#E7E2DB",
      95: "#F6F0E9",
      98: "#FFF8F1",
      99: "#FFFBFF",
      100: "#FFFFFF"
    },
    neutralWhite: {
      'background': 'var(--chakra-colors-neutral-100)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-neutral-100)',
      'surface-low': 'var(--chakra-colors-neutral-96)',
      'surface': 'var(--chakra-colors-neutral-94)',
      'surface-high': 'var(--chakra-colors-neutral-92)',
      'surface-highest': 'var(--chakra-colors-neutral-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'outline': 'var(--chakra-colors-neutral-50)',
      'outline-dim': 'var(--chakra-colors-neutral-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralLight: {
      'background': 'var(--chakra-colors-neutral-98)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-neutral-100)',
      'surface-low': 'var(--chakra-colors-neutral-96)',
      'surface': 'var(--chakra-colors-neutral-94)',
      'surface-high': 'var(--chakra-colors-neutral-92)',
      'surface-highest': 'var(--chakra-colors-neutral-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'outline': 'var(--chakra-colors-neutral-60)',
      'outline-dim': 'var(--chakra-colors-neutral-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralDark: {
      'background': 'var(--chakra-colors-neutral-4)',
      'on-background': 'var(--chakra-colors-neutral-90)',
      'surface-lowest': 'var(--chakra-colors-neutral-0)',
      'surface-low': 'var(--chakra-colors-neutral-10)',
      'surface': 'var(--chakra-colors-neutral-12)',
      'surface-high': 'var(--chakra-colors-neutral-17)',
      'surface-highest': 'var(--chakra-colors-neutral-22)',
      'on-surface': 'var(--chakra-colors-neutral-90)',
      'outline': 'var(--chakra-colors-neutral-60)',
      'outline-dim': 'var(--chakra-colors-neutral-30)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    neutralVariantWhite: {
      'background': 'var(--chakra-colors-neutralVariant-100)',
      'on-background': 'var(--chakra-colors-neutralVariant-10)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-100)',
      'surface-low': 'var(--chakra-colors-neutralVariant-96)',
      'surface': 'var(--chakra-colors-neutralVariant-94)',
      'surface-high': 'var(--chakra-colors-neutralVariant-92)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-90)',
      'on-surface': 'var(--chakra-colors-neutralVariant-10)',
      'outline': 'var(--chakra-colors-neutralVariant-50)',
      'outline-dim': 'var(--chakra-colors-neutralVariant-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralVariantLight: {
      'background': 'var(--chakra-colors-neutralVariant-98)',
      'on-background': 'var(--chakra-colors-neutralVariant-10)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-100)',
      'surface-low': 'var(--chakra-colors-neutralVariant-96)',
      'surface': 'var(--chakra-colors-neutralVariant-94)',
      'surface-high': 'var(--chakra-colors-neutralVariant-92)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-90)',
      'on-surface': 'var(--chakra-colors-neutralVariant-10)',
      'outline': 'var(--chakra-colors-neutralVariant-50)',
      'outline-dim': 'var(--chakra-colors-neutralVariant-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralVariantDark: {
      'background': 'var(--chakra-colors-neutralVariant-4)',
      'on-background': 'var(--chakra-colors-neutralVariant-90)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-0)',
      'surface-low': 'var(--chakra-colors-neutralVariant-10)',
      'surface': 'var(--chakra-colors-neutralVariant-12)',
      'surface-high': 'var(--chakra-colors-neutralVariant-17)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-22)',
      'on-surface': 'var(--chakra-colors-neutralVariant-90)',
      'outline': 'var(--chakra-colors-neutralVariant-40)',
      'outline-dim': 'var(--chakra-colors-neutralVariant-30)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    primaryWhite: {
      'background': 'var(--chakra-colors-primary-100)',
      'on-background': 'var(--chakra-colors-neutral-20)',
      'surface-lowest': 'var(--chakra-colors-primary-100)',
      'surface-low': 'var(--chakra-colors-primary-96)',
      'surface': 'var(--chakra-colors-primary-94)',
      'surface-high': 'var(--chakra-colors-primary-92)',
      'surface-highest': 'var(--chakra-colors-primary-90)',
      'on-surface': 'var(--chakra-colors-neutral-20)',
      'container': 'var(--chakra-colors-primary-95)',
      'outline': 'var(--chakra-colors-neutral-60)',
      'outline-dim': 'var(--chakra-colors-neutral-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    primaryLight: {
      'background': 'var(--chakra-colors-primary-99)',
      'on-background': 'var(--chakra-colors-primary-20)',
      'surface-lowest': 'var(--chakra-colors-primary-100)',
      'surface-low': 'var(--chakra-colors-primary-96)',
      'surface': 'var(--chakra-colors-primary-94)',
      'surface-high': 'var(--chakra-colors-primary-92)',
      'surface-highest': 'var(--chakra-colors-primary-90)',
      'on-surface': 'var(--chakra-colors-primary-20)',
      'container': 'var(--chakra-colors-primary-95)',
      'outline': 'var(--chakra-colors-neutral-60)',
      'outline-dim': 'var(--chakra-colors-neutral-80)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    primaryMedium: {
      'background': 'var(--chakra-colors-primary-40)',
      'on-background': 'var(--chakra-colors-primary-100)',
      'surface-lowest': 'var(--chakra-colors-primary-40)',
      'surface-low': 'var(--chakra-colors-primary-40)',
      'surface': 'var(--chakra-colors-primary-50)',
      'surface-high': 'var(--chakra-colors-primary-50)',
      'surface-highest': 'var(--chakra-colors-primary-50)',
      'on-surface': 'var(--chakra-colors-primary-100)',
      'container': 'var(--chakra-colors-primary-50)',
      'outline': 'var(--chakra-colors-neutral-80)',
      'outline-dim': 'var(--chakra-colors-neutral-70)',
      'primary': 'var(--chakra-colors-primary-90)',
    },
    primaryDark: {
      'background': 'var(--chakra-colors-primary-4)',
      'on-background': 'var(--chakra-colors-primary-100)',
      'surface-lowest': 'var(--chakra-colors-primary-0)',
      'surface-low': 'var(--chakra-colors-primary-10)',
      'surface': 'var(--chakra-colors-primary-12)',
      'surface-high': 'var(--chakra-colors-primary-17)',
      'surface-highest': 'var(--chakra-colors-primary-22)',
      'on-surface': 'var(--chakra-colors-primary-100)',
      'outline': 'var(--chakra-colors-neutral-50)',
      'outline-dim': 'var(--chakra-colors-neutral-30)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    secondaryWhite: {
      'background': 'var(--chakra-colors-secondary-100)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-secondary-100)',
      'surface-low': 'var(--chakra-colors-secondary-96)',
      'surface': 'var(--chakra-colors-secondary-94)',
      'surface-high': 'var(--chakra-colors-secondary-92)',
      'surface-highest': 'var(--chakra-colors-secondary-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'container': 'var(--chakra-colors-secondary-95)',
      'primary': 'var(--chakra-colors-secondary-70)',
    },
    secondaryLight: {
      'background': 'var(--chakra-colors-secondary-99)',
      'on-background': 'var(--chakra-colors-neutral-30)',
      'surface-lowest': 'var(--chakra-colors-secondary-100)',
      'surface-low': 'var(--chakra-colors-secondary-96)',
      'surface': 'var(--chakra-colors-secondary-94)',
      'surface-high': 'var(--chakra-colors-secondary-92)',
      'surface-highest': 'var(--chakra-colors-secondary-90)',
      'on-surface': 'var(--chakra-colors-neutral-30)',
      'container': 'var(--chakra-colors-secondary-95)',
      'primary': 'var(--chakra-colors-secondary-70)',
    },
    secondaryDark: {
      'background': 'var(--chakra-colors-secondary-4)',
      'on-background': 'var(--chakra-colors-neutral-90)',
      'surface-lowest': 'var(--chakra-colors-secondary-0)',
      'surface-low': 'var(--chakra-colors-secondary-10)',
      'surface': 'var(--chakra-colors-secondary-12)',
      'surface-high': 'var(--chakra-colors-secondary-17)',
      'surface-highest': 'var(--chakra-colors-secondary-22)',
      'on-surface': 'var(--chakra-colors-neutral-95)',
      'outline': 'var(--chakra-colors-secondary-40)',
      'primary': 'var(--chakra-colors-secondary-70)'
    },
    tertiaryWhite: {
      'background': 'var(--chakra-colors-tertiary-100)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-tertiary-100)',
      'surface-low': 'var(--chakra-colors-tertiary-96)',
      'surface': 'var(--chakra-colors-tertiary-94)',
      'surface-high': 'var(--chakra-colors-tertiary-92)',
      'surface-highest': 'var(--chakra-colors-tertiary-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'outline': 'var(--chakra-colors-tertiary-60)',
      'container': 'var(--chakra-colors-tertiary-95)',
      'primary': 'var(--chakra-colors-tertiary-70)',
    },
    tertiaryLight: {
      'background': 'var(--chakra-colors-tertiary-98)',
      'on-background': 'var(--chakra-colors-tertiary-10)',
      'surface-lowest': 'var(--chakra-colors-tertiary-100)',
      'surface-low': 'var(--chakra-colors-tertiary-96)',
      'surface': 'var(--chakra-colors-tertiary-94)',
      'surface-high': 'var(--chakra-colors-tertiary-92)',
      'surface-highest': 'var(--chakra-colors-tertiary-90)',
      'on-surface': 'var(--chakra-colors-tertiary-10)',
      'container': 'var(--chakra-colors-tertiary-95)',
      'outline': 'var(--chakra-colors-tertiary-60)',
      'primary': 'var(--chakra-colors-tertiary-70)',
    },
    tertiaryDark: {
      'background': 'var(--chakra-colors-tertiary-4)',
      'on-background': 'var(--chakra-colors-tertiary-90)',
      'surface-lowest': 'var(--chakra-colors-tertiary-0)',
      'surface-low': 'var(--chakra-colors-tertiary-10)',
      'surface': 'var(--chakra-colors-tertiary-12)',
      'surface-high': 'var(--chakra-colors-tertiary-17)',
      'surface-highest': 'var(--chakra-colors-tertiary-22)',
      'on-surface': 'var(--chakra-colors-tertiary-98)',
      'outline': 'var(--chakra-colors-tertiary-40)',
      'primary': 'var(--chakra-colors-tertiary-70)'
    },
  }
});

export default theme;
