import { Figtree, Alegreya_SC } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const alegreya = Alegreya_SC({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
})

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${alegreya.className} ${figtree.className}`}>
      {/* <body className={alegreya.className}> */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
